### ISSUE TITLE
[TERM REQUEST] Mathematical Markup Language

### ISSUE THREAD

**Issue by egonw** [VHP4Safety/glossary#29]
**What would be a label for the terms to categorize the entries in the glossary?**
MathML

**What is the definition of the term?**
Mathematical Markup Language, https://www.w3.org/Math/

**Is there an ontology that has this term?**
?

**Additional context**
Result from the 2022-09-23 Actor Analysis meeting in Utrecht.

**Comment by ozancinar** [comment]
An entry has been added under the Tool/service-related terms.
