### ISSUE TITLE
[TERM REQUEST] **Proteochemometric**

### ISSUE THREAD

**Issue by LindeSchoenmaker** [VHP4Safety/glossary#35]
**What would be a label for the terms to categorize the entries in the glossary?**
Proteochemometric (PCM)

**What is the definition of the term?**
Mathematical models that can be used to predict the biological properties (mainly bioactivity) of compounds on proteins from the knowledge of their (chemical) structure.

**Is there an ontology that has this term?**
No

**Additional context**
This is a tool-related term, PCM is similar but not the same as QSAR. In QSAR modeling protein characteristics are typically not included, whereas in PCM modeling the bioactivity of multiple ligands against multiple related protein targets is simultaneously taken into account

**Comment by ozancinar** [comment]
Added to the glossary (under Tool/service-related terms) with the proposed definition.
