### ISSUE TITLE
[TERM REQUEST] **bioactivity**

### ISSUE THREAD

**Issue by LindeSchoenmaker** [VHP4Safety/glossary#36]
**What would be a label for the terms to categorize the entries in the glossary?**
Bioactivity

**What is the definition of the term?**
The affinity and/or potency of a compound for a protein target

**Is there an ontology that has this term?**
No

**Additional context**
Used for compound-protein interaction prediction (by for example QSAR & PCM models)

**Comment by ozancinar** [comment]
Added to the glossary (under Adverse-Outcome Pathway-related terms) with the proposed definition.
