### ISSUE TITLE
[TERM REQUEST] widget

### ISSUE THREAD

**Issue by egonw** [VHP4Safety/glossary#41]
**What would be a label for the terms to categorize the entries in the glossary?**
Widget.

**What is the definition of the term?**
"a small software application that is designed to provide a specific piece of information (such as news, weather, or traffic updates) or a specific function (such as taking notes or controlling another application) on demand"

**Is there an ontology that has this term?**
Not on BioPortal. But it's given in this dictionary: https://www.merriam-webster.com/dictionary/widget

**Additional context**
Used in the Social Wall item I posted today (and the term used by ELIXIR TeSS):

![image](https://user-images.githubusercontent.com/26721/214121170-aabe1b4f-b624-4a62-a13c-4ae4ec41c1cd.png)

**Comment by ozancinar** [comment]
An entry has been made.
