### ISSUE TITLE
check D1.1.1 abbreviations

### ISSUE THREAD

**Issue by egonw** [VHP4Safety/glossary#42]
- [x] AAI | Authentication and Authorization Infrastructure
- [x] AOP | adverse outcome pathway
- [x] API | Application Programming Interface
- [x] EOSC | European Open Science Cloud
- [x] FAIR | Findable, Accessible, Interoperable, Reusable
- [x] HTML | HyperText Markup Language
- [x] HTTPS | Hypertext Transfer Protocol Secure
- [x] ICT | Information and Communications Technology
- [x] OWL | Web Ontology Language
- [x] RDFa | Resource Description Framework in Attributes
- [x] SPARQL | SPARQL Protocol and RDF Query Language
- [x] UI | user interface
- [x] URL | Uniform Resource Locator
- [x] VHP | Virtual Human Platform
- [x] WP1.1 | Work Package 1.1

**Comment by ozancinar** [comment]
All abbreviations have been checked. I added 'JSON' to the list of abbreviations as well. It was in the text but not in the list of abbreviations.
