### ISSUE TITLE
[TERM REQUEST] Data Management Plan (DMP)

### ISSUE THREAD

**Issue by johannehouweling** [VHP4Safety/glossary#44]
**What would be a label for the terms to categorize the entries in the glossary?**
Tool/service-related terms

**What is the definition of the term?**
Data management plans serve to address the what, how, who, and where of data management by formally outlining the roles, responsibilities and activities for managing data during and after research in alignment with FAIR principles
[https://doi.org/10.1016/B978-0-08-102295-5.10531-1](url).

**Is there an ontology that has this term?**
?

**Additional context**
?

**Comment by ozancinar** [comment]
Added to the glossary.
