### ISSUE TITLE
[TERM REQUEST] ECHA

### ISSUE THREAD

**Issue by johannehouweling** [VHP4Safety/glossary#47]
**What would be a label for the terms to categorize the entries in the glossary?**
ECHA: European Chemical Agency  

**What is the definition of the term?**
The European Chemicals Agency is an agency of the European Union which manages the technical and administrative aspects of the implementation of the European Union regulation called Registration, Evaluation, Authorisation and Restriction of Chemicals. [ref](https://echa.europa.eu/)

**Is there an ontology that has this term?**
If there is an ontology that has an entry that matches your, please report here which ontology that is, and what the ontology identifier of that term is.

**Additional context**
Add any other context or information about the term request here.

**Comment by ozancinar** [comment]
The term has been added to the glossary.
