### ISSUE TITLE
[TERM REQUEST] EST is not a correct abbreviation

### ISSUE THREAD

**Issue by senseibelbi** [VHP4Safety/glossary#51]
For Embryonic Stem Cells, the international convention is ESC not EST,
For induced pluripotent stem cells it's iPSC

**Comment by ozancinar** [comment]
Thank you for the warning, the change has been made. Just for checking: Should this apply to the term in the description, hESTc? Should it also be hESCc in the same manner?

**Comment by senseibelbi** [comment]
Thanks for the change ! hESCs would work in the case of human embryonic stem cells, general term is ESC, although in VHP4S we use iPSCs  and not ESCs if i am not mistaken

**Comment by ozancinar** [comment]
Thanks for the reply. So, if I understand it correctly, in the context of VHP4Safety, it'd be better to change the description from "Typically combined like: hESTc (human, cardiac)" to "Typically combined like: iPSCs (human, cardiac)". 

Also, I am not sure if this is a sufficient and clear description. We would appreciate it if you can provide a better description for "Embryonic Stem Cell" if you have expertise on it.

**Comment by senseibelbi** [comment]
I would just include these:

(h)ESCs -> (human) Embryonic Stem Cells -> hESCs are pluripotent stem cells derived from the inner cell mass of a blastocyst (an early-stage pre-implantation embryo). These cells are characterised by their ability to differentiate into any cell type of the three germ layers: ectoderm, mesoderm, and endoderm. They are also known for their self-renewal capability, meaning they can proliferate indefinitely in culture while maintaining their pluripotency.

iPSCs -> induced Pluripotent Stem Cells -> iPSCs are a type of pluripotent stem cell that can be generated directly from adult cells. The process of creating iPSCs involves reprogramming differentiated somatic cells (such as skin or blood cells) by introducing specific genes that reset the cells to a pluripotent state. This reprogramming allows iPSCs to develop into almost any cell type in the body, similarly to hESCs, making them highly valuable for regenerative medicine, disease modelling, and drug discovery.

For Cardiac Stem cells i guess it would be CSC, but CSC could also mean cancer stem cells. Since we don't use these in the project might as well not mention the abbreviation for this.  :)

**Comment by ozancinar** [comment]
The old entry is now converted to (h)ESCs entry, and a new entry for iPSCs has been added to the glossary. Thank you for your contribution.

**Comment by Chris-Evelo** [comment]
Note that the more common meaning of "EST" is "Expressed Sequence Tag", which is also relevant in this field
