### ISSUE TITLE
[TERM REQUEST] template

### ISSUE THREAD

**Issue by egonw** [VHP4Safety/glossary#52]
**What would be a label for the terms to categorize the entries in the glossary?**

template

**What is the definition of the term?**
"a thing that is used as a model for producing other similar examples", source: https://www.oxfordlearnersdictionaries.com/definition/english/template

**Is there an ontology that has this term?**
See above link. Defined by Oxford English Dictionary.

**Additional context**
Add any other context or information about the term request here.

**Comment by ozancinar** [comment]
The term has been added to the glossary.
