### ISSUE TITLE
[TERM REQUEST] stakeholder

### ISSUE THREAD

**Issue by egonw** [VHP4Safety/glossary#54]
**What would be a label for the terms to categorize the entries in the glossary?**
Labels are used for categorizating the entries in the glossary, e.g., terms that are related to toxicology, adverse outcome pathways, etc.

Stakeholder

**What is the definition of the term?**

@aniekdewinter, Isaac, please add the definition of "User here".

**Is there an ontology that has this term?**

If there is an ontology that has an entry that matches your, please report here which ontology that is, and what the ontology identifier of that term is.

**Additional context**

Add any other context or information about the term request here.

@aniekdewinter, e.g. that (or how) it is different from User.

**Comment by egonw** [comment]
ping @aniekdewinter

**Comment by ozancinar** [comment]
I guess this was my mistake. The term stakeholder has already been [added](https://glossary.vhp4safety.nl/#VHP0000113) through another issue [here](https://github.com/VHP4Safety/glossary/issues/59). I'll close this issue as well.
