### ISSUE TITLE
Stakeholder

### ISSUE THREAD

**Issue by aniekdewinter** [VHP4Safety/glossary#59]
**What would be a label for the terms to categorize the entries in the glossary?**
Social sciences

Stakeholder

**What is the definition of the term?**
Those who hold a stake and/or can influence decision-making on a specific issue​

**Is there an ontology that has this term?**
If there is an ontology that has an entry that matches your, please report here which ontology that is, and what the ontology identifier of that term is.

**Additional context**
Add any other context or information about the term request here.

**Comment by ozancinar** [comment]
Thank you fro your contribution. The term has been added to the glossary and can be found [here](https://glossary.vhp4safety.nl/#VHP0000113). 

While adding the term, its description has been slightly changed ("those" -> "a person or an organization") as this would fit better to the general format of descriptions in the glossary. Please let us know if this change does not give a correct description.

**Comment by aniekdewinter** [comment]
Thank you Ozan! Could you maybe change it into "a person or a group of people"? As it could also refer to e.g. "animal-lovers" as a group, but that's not necessarily an organization.

**Comment by ozancinar** [comment]
Sure, the change has been made. Thanks for the feedback.
