### ISSUE TITLE
incident postmortem

### ISSUE THREAD

**Issue by egonw** [VHP4Safety/glossary#60]
**What would be a label for the terms to categorize the entries in the glossary?**
incident postmortem

Aliases: post-mortem, postmortem, and "post-incident review"

**What is the definition of the term?**
An incident postmortem is a event that "brings people together to discuss the details of an incident: why it happened, its impact, what actions were taken to mitigate it and resolve it, and what should be done to prevent it from happening again."

**Is there an ontology that has this term?**
Not sure, but here is a good description: https://www.atlassian.com/incident-management/postmortem

**Comment by ozancinar** [comment]
The term has been added to the glossary.
