### ISSUE TITLE
[TERM REQUEST] SCRUM

### ISSUE THREAD

**Issue by mirthhe** [VHP4Safety/glossary#64]
### Label

SCRUM

### Definition

An agile way of working as a development team that uses time-boxed iterations called sprints to focus on fully executing smaller increments of a larger product. It includes clear bite-sized tasks, regular discussions and collaborative review. It tackles issues such as vague long term goals, poor teamwork and inefficient timespending.

**Comment by ozancinar** [comment]
The term has been added [here](https://vhp4safety.github.io/glossary#VHP0000119) with suggested definition. Thanks for your contribution. 

Just a question though --Is SCRUM the abbreviation of a term, or is it really called just SCRUM? If it is the abbreviation of a longer term, we can modify the entry in the glossary.
