### ISSUE TITLE
[TERM REQUEST] Sprint

### ISSUE THREAD

**Issue by mirthhe** [VHP4Safety/glossary#65]
### Label

Sprint

### Definition

A fixed time-box, usually 1-4 weeks, used in the SCRUM method of working. Per sprint, each teammember works on selected tasks which they can (likely) finish within the sprint. Each sprint has meetings to plan the sprint, review the finished tasks and reflect to improve productivity..

**Comment by ozancinar** [comment]
The term has been added [here](https://vhp4safety.github.io/glossary#VHP0000120) with suggested definition. Thanks for your contribution.
