### ISSUE TITLE
[TERM REQUEST] Scrum Master

### ISSUE THREAD

**Issue by mirthhe** [VHP4Safety/glossary#67]
### Label

Scrum Master

### Definition

A person's role when working in the SCRUM method. They ensure the team follows the scrum practices and that the backlog, sprint, user stories and epics are clear.

**Comment by ozancinar** [comment]
The term has been added [here](https://vhp4safety.github.io/glossary#VHP0000122) with minor modifications to the suggested definition to make it similar to the rhetoric of the other terms. Please comment in this issue if you are not happy with the edits and want to change the description again. Thanks for your contribution.
