### ISSUE TITLE
[TERM REQUEST] Product Owner

### ISSUE THREAD

**Issue by mirthhe** [VHP4Safety/glossary#68]
### Label

Product Owner

### Definition

A key rol in SCRUM. They have a clear view of the project's long term goals and the teammembers' expertises. They review the epics and user stories and prioritize the tasks in the backlog.

**Comment by ozancinar** [comment]
The term has been added [here](https://vhp4safety.github.io/glossary#VHP0000123) with minor modifications to the suggested definition to make it similar to the rhetoric of the other terms. Please comment in this issue if you are not happy with the edits and want to change the description again. Thanks for your contribution.
