### ISSUE TITLE
[TERM REQUEST] SCRUM Board

### ISSUE THREAD

**Issue by mirthhe** [VHP4Safety/glossary#69]
### Label

SCRUM Board

### Definition

The documentation of the tasks in the backlog, tasks in the current sprint, the user stories, the epics and the completed tasks when working in SCRUM. Usually shared and edited through GitHub Projects, Notion or similar tools.

**Comment by ozancinar** [comment]
The term has been added [here](https://vhp4safety.github.io/glossary#VHP0000124) with suggested definition. Thanks for your contribution.
