### ISSUE TITLE
[TERM REQUEST] Sprint Planning

### ISSUE THREAD

**Issue by mirthhe** [VHP4Safety/glossary#70]
### Label

Sprint Planning

### Definition

A meeting at the beginning of each sprint where the team selects tasks from the backlog to work on during that sprint. The team will also assign members to each task and discuss how they plan on completing them.

**Comment by ozancinar** [comment]
The term has been added [here](https://vhp4safety.github.io/glossary#VHP0000125) with suggested definition. Thanks for your contribution.
