### ISSUE TITLE
[TERM REQUEST] Sprint Review

### ISSUE THREAD

**Issue by mirthhe** [VHP4Safety/glossary#71]
### Label

Sprint Review

### Definition

A meeting at the end of a sprint where the team presents their work and discuss any issues. The goal is to review the completed tasks and adapt the backlog accordingly. This meeting can be combined with the Sprint Retrospective.

**Comment by ozancinar** [comment]
The term has been added [here](https://vhp4safety.github.io/glossary#VHP0000126) with suggested definition. Thanks for your contribution.
