### ISSUE TITLE
[TERM REQUEST] Sprint Retrospective

### ISSUE THREAD

**Issue by mirthhe** [VHP4Safety/glossary#72]
### Label

Sprint Retrospective

### Definition

A meeting after the Sprint Review where the team reflects on the sprint's process. It focuses on what went well, what didn't and how the team can improve in the next sprint.

**Comment by ozancinar** [comment]
The term has been added [here](https://vhp4safety.github.io/glossary#VHP0000127) with minor modifications to the suggested definition to make it similar to the rhetoric of the other terms. Please comment in this issue if you are not happy with the edits and want to change the description again. Thanks for your contribution.
