### ISSUE TITLE
[TERM REQUEST] User Story

### ISSUE THREAD

**Issue by mirthhe** [VHP4Safety/glossary#73]
### Label

User Story

### Definition

A simple, clear description of a desired feature or functionality from the perspective of the end user. Typically follows the format: "As as [user], I want [feature], so that [benefit].". Each task in the backlog should be contributing to as user story, each user story should be contributing to an epic.

**Comment by ozancinar** [comment]
The term has been added [here](https://vhp4safety.github.io/glossary#VHP0000128) with suggested definition. Thanks for your contribution.
