### ISSUE TITLE
[TERM REQUEST] Epic

### ISSUE THREAD

**Issue by mirthhe** [VHP4Safety/glossary#74]
### Label

Epic

### Definition

A long-term goal or general feature of the final product. Epics are broken down into user stories, user stories are broken down into tasks. By completing tasks in each sprint, the epic will gradually be reached.

**Comment by ozancinar** [comment]
The term has been added [here](https://vhp4safety.github.io/glossary#VHP0000129) with minor modifications to the suggested definition. Please comment in this issue if you are not happy with the edits and want to change the description again. Thanks for your contribution.
