### ISSUE TITLE
[TERM REQUEST] DoD (Definition of Done)

### ISSUE THREAD

**Issue by mirthhe** [VHP4Safety/glossary#75]
### Label

Definition of Done

### Definition

A shared understanding among the team of when a task is considered as "done". It ensures work is completed to a certain standard before it is accepted. This might include specific documentation, review by another team member or discussion during the Sprint Review.

### Acronym

DoD

**Comment by ozancinar** [comment]
The term has been added [here](https://vhp4safety.github.io/glossary#VHP0000130) with suggested definition. Thanks for your contribution.
