### ISSUE TITLE
[TERM REQUEST] Please add this glossary term: Blood Brain Barrier

### ISSUE THREAD

**Issue by Chris-Evelo** [VHP4Safety/glossary#78]
### Label

Blood Brain Barrier

### Definition

These barriers protect the brain and spinal cord from both toxic and pathogenic agents in the blood. The BBB is formed by extensive tight junctions between vascular epithelial cells, which are polarized into luminal (blood-facing) and abluminal (brain-facing) plasma membrane domains.

### Acronym

BBB

**Comment by ozancinar** [comment]
The term has been added with minor edits under Toxicology section [here](https://vhp4safety.github.io/glossary#VHP0000132). Please re-open or comment in this issue if you have further editions to the term. Thank you for your contribution.
