### ISSUE TITLE
[TERM REQUEST] pCHEMBL

### ISSUE THREAD

**Issue by egonw** [VHP4Safety/glossary#79]
### Label

pCHEMBL

### Definition

not sure, see https://chembl.gitbook.io/chembl-interface-documentation/frequently-asked-questions/chembl-data-questions#what-is-pchembl

### Acronym

pCHEMBL

### Context

See https://chembl.gitbook.io/chembl-interface-documentation/frequently-asked-questions/chembl-data-questions#what-is-pchembl for the definition. pCHEMBL is used by one of our cloud servics

**Comment by ozancinar** [comment]
The term has been added [here](https://vhp4safety.github.io/glossary#VHP0000143) under the Toxicology in General section.
